# Generated by Django 2.1.7 on 2019-04-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taste', models.CharField(max_length=200, verbose_name='口味')),
                ('Stime', models.CharField(max_length=200, verbose_name='接单时间')),
                ('Etime', models.CharField(max_length=200, verbose_name='订单完成时间')),
                ('Uname', models.CharField(max_length=200, verbose_name='用户名')),
                ('Gender', models.CharField(max_length=200, verbose_name='性别')),
                ('Phone', models.CharField(max_length=200, verbose_name='电话')),
                ('Status', models.CharField(max_length=200, verbose_name='订单状态')),
                ('Number', models.CharField(max_length=200, verbose_name='订单号')),
            ],
            options={
                'verbose_name': '订单表',
            },
        ),
    ]
