# Generated by Django 2.2.4 on 2019-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modClear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(max_length=200, verbose_name='清理日期')),
            ],
            options={
                'verbose_name': '清理表',
            },
        ),
        migrations.CreateModel(
            name='modOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taste', models.CharField(max_length=200, verbose_name='口味')),
                ('Stime', models.DateTimeField(verbose_name='接单时间')),
                ('Etime', models.DateTimeField(max_length=200, verbose_name='订单完成时间')),
                ('Uname', models.CharField(max_length=200, verbose_name='用户名')),
                ('Gender', models.CharField(max_length=200, verbose_name='性别')),
                ('Phone', models.CharField(max_length=200, verbose_name='电话')),
                ('Status', models.CharField(max_length=200, verbose_name='订单状态')),
                ('Number', models.CharField(max_length=200, verbose_name='订单号')),
                ('Pos', models.IntegerField(default=0, verbose_name='仓位号')),
            ],
            options={
                'verbose_name': '订单表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.CharField(max_length=2, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
    ]
