# Generated by Django 2.2 on 2019-04-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeClient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modClear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200, verbose_name='清理日期')),
            ],
            options={
                'verbose_name': '清理表',
            },
        ),
    ]
