# Generated by Django 2.2 on 2019-07-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeClient', '0003_auto_20190528_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='modorder',
            name='pos',
            field=models.IntegerField(default=0, verbose_name='仓位号'),
        ),
    ]
