# Generated by Django 2.2 on 2019-07-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeClient', '0004_modorder_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modorder',
            old_name='pos',
            new_name='Pos',
        ),
    ]
