# Generated by Django 2.2.4 on 2019-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeClient', '0005_auto_20190703_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.CharField(max_length=2, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('picture', models.CharField(max_length=100, verbose_name='照片')),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
    ]
